### PR TITLE
Started with 4.0

### PR DESCRIPTION
**Pull request by SebastianStehle**
Todos

* [x] Fix samples
* [x] Build sample with separate Client?

### CODE REVIEW

**Comment by richorama** [comment]
There is now a dotnet 6.0 runner, which might fix the failing CI

**Comment by SebastianStehle** [comment]
Btw: With Orleans 4.0 they seem to focus on the Host interface to setup everything. So everything except "TestHostCohosted2" is basically obsolete or requires some rework. I only tested `TestHostCohosted2` so far and it works fine, but I am confused with the serializers.

**Comment by richorama** [comment]
well it builds @ElanHasson

**Comment by ElanHasson** [comment]
Nice! 

There is currently a problem with ado providers, so I won't be able to adopt yet

**Comment by runenilsenoe** [comment]
Anything in can help with to get this ready for prerelease?

**Comment by SebastianStehle** [comment]
It is actually ready, I think. I do not know where the merge conflicts are coming from, but we can fix them.

I think we just need a feature branch for that and also enable the CI for this feature so that we can release this as a prerelease version and keep the master for hotfixes.

**Comment by koenbeuk** [comment]
@SebastianStehle On NuGet, OrleansDashboard.Core 4.0.0-preview1 is not available, hence OrleansDashboard 4.0.0-preview1 can't be installed through NuGet. Any plans on fixing this? Thanks!

**Review by richorama — APPROVED** [review]

**Pull request merged**
