### PR TITLE
JSON performance improved using System.Text.Json

### PR DESCRIPTION
**Pull request by SebastianStehle**

### CODE REVIEW

**Comment by SebastianStehle** [comment]
Thx.

**Comment by richorama** [comment]
I think I have a bug in the GH actions configuration, as it hasn't published to nuget. I'll look into it when I get the chance..

**Comment by SebastianStehle** [comment]
Can you push it to nuget manually?

**Comment by SebastianStehle** [comment]
Or add me in nuget if you want...mail2stehle@googlemail.com / sebastianstehle

**Comment by richorama** [comment]
Now sorted

**Pull request merged**
