### PR TITLE
Use minimal MVC components

### PR DESCRIPTION
**Pull request by rikbosch**
This PR reduces memory usage by configuring (and referencing) only the used asp.net mvc core components.

### CODE REVIEW

**Comment by DixonDs** [comment]
@rikbosch Just curious, do you have any numbers supporting reduced memory usage?

**Comment by rikbosch** [comment]
@DixonDs no concrete numbers, this is however the 'default' AddMvc implementation:

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc/MvcServiceCollectionExtensions.cs#L25-L56

which registers a lot of components, the dashboard does not use, especially razor views.

I think, in fact, we can skip MVC altogether and just build an implementation of the dashboard using https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing. (More or less like the previous dashboard implementation)

**Comment by richorama** [comment]
Looks good to me. @DixonDs any thoughts?

**Comment by DixonDs** [comment]
@richorama I am good as long as it works :) I am just a bit suspicious to any optimizations without any tests (at least manual) showing their effect (positive or at least non-negative)

**Comment by richorama** [comment]
passes manual testing :¬)

Thanks for your contribution @rikbosch

**Pull request merged**
