### PR TITLE
Feat/reminders/add filters

### PR DESCRIPTION
**Pull request by oreporan**
Another issue which bugged me was that it remembered previous reminder pages in my browser, though that page wasn't the last page anymore. It would return an empty list of Reminders.

This PR reroutes (by calculating the lastPage and creating a new request) to the last page which has reminders

BTW - good time to say this is a great project, keep up the good work

### CODE REVIEW

**Comment by richorama** [comment]
Thank you!

**Comment by oreporan** [comment]
@richorama any updates ? new version?

**Comment by richorama** [comment]
@oreporan sorry for the delay. I have manually pushed a version up to nuget. For some reason appveyor has given up :¬/

**Comment by richorama** [comment]
version 1.5.5

**Comment by oreporan** [comment]
Getting an error with .Net framework 4.6.2

**Pull request merged**
