### PR TITLE
Allow setting a BasePath in self host mode like /dashboard

### PR DESCRIPTION
**Pull request by jms69**
In self host mode I require that there is a base path such as http://localhost:8000/dashboard.

I added a BasePath string property in DashboardOptions.

### CODE REVIEW

**Comment by SebastianStehle** [comment]
Why are you not hosting it by yourself. You have more options then, e.g. I am securing dashboard with Identity Server:

https://github.com/Squidex/squidex/blob/master/src/Squidex/Areas/OrleansDashboard/Startup.cs

**Comment by jms69** [comment]
So this is for service fabric where the Silo is in one service and a webapi layer is in another service.  I am using the dashboard for diagnostics.  

I move to hosting the dashboard in the webapi layer with a /dashboard vroot.  This mostly worked except for the Logstream.  The logstream was giving logs on the webapi layer and not the Orleans silo.  In need to run the dashboard on the silo service.

**Comment by SebastianStehle** [comment]
The log stream should be used for development only in my opinion. You will only get the logs from a single server and with the load balancer it is totally random which server it is.

**Comment by jms69** [comment]
I totally agree.  So everything works locally and in my DEV clusters.  Then I deploy in a Test cluster and nothing works.  Client layer has errors connecting to the silo.  I cannot remote into the cluster.  Logs teams are delayed by 5 mins.  Having the dashboard in to silo, I can see if the silos are the issue and all silos have joined.  If there is a log stream for one machine I can at least see some errors.  One such case was a mistake in logic used the local DEV azure storage string when I deployed to the cloud.

I wanted to put this dashboard behind a reverse proxy and expose it as needed.

Is there a technical reason having the ability to specify a base path when running in self host a bad idea?

**Comment by SebastianStehle** [comment]
No, it is fine. We should just avoid putting too much http settings in the options.

**Pull request merged**
