### PR TITLE
add version API and display it next to theme buttons

### PR DESCRIPTION
**Pull request by oreporan**
The orleans dashboard should probably show its version somewhere, this info is available in Visual Studio by searching for the Nuget package, but this makes it more simple to know what version of the dashboard you have

### CODE REVIEW

**Comment by richorama** [comment]
Thanks - keep them coming :¬)

**Comment by oreporan** [comment]
Happily, how often do you release a version?

**Comment by richorama** [comment]
I generally try to keep in step with Orleans versions, or when a significant new feature is added.

I think you additions warrant a release. Shall I go ahead, or are you planning to drop some more PRs???

**Comment by oreporan** [comment]
Nah, its almost 19:00 where I'm from, calling it a day :)

**Comment by richorama** [comment]
👍 I'll make a release tomorrow

**Comment by richorama** [comment]
attempts to make a release have failed, for some reason the project has decided to stop emitting a nupkg :¬/

I'll take another look at it later...

**Pull request merged**
