### PR TITLE
Reduced dependency footprint.

### PR DESCRIPTION
**Pull request by SebastianStehle**

### CODE REVIEW

**Comment by richorama** [comment]
```
Errors in C:\projects\orleansdashboard\OrleansDashboard\OrleansDashboard.csproj
    NU1605: Detected package downgrade: System.Collections.Immutable from 1.5.0 to 1.4.0. Reference the package directly from the project to select a different version.
     OrleansDashboard -> Microsoft.AspNetCore.Hosting 2.1.1 -> System.Reflection.Metadata 1.6.0 -> System.Collections.Immutable (>= 1.5.0)
     OrleansDashboard -> System.Collections.Immutable (>= 1.4.0)
```

**Comment by SebastianStehle** [comment]
It works on my machine ;) ... Will check it on Monday.

**Comment by SebastianStehle** [comment]
Yes, I see it. But I do not understand it.

**Comment by richorama** [comment]
I'll see if I can reproduce it tomorrow.

**Comment by SebastianStehle** [comment]
Could you reproduce it?

**Comment by richorama** [comment]
No, I spent quite a bit of time trying to repro it, and fiddling with the app veyor build. Couldn't work it out :¬/

**Comment by SebastianStehle** [comment]
Do you get the same compile error when you pull it locally?

**Comment by richorama** [comment]
No, I only see the error in AppVeyor.

**Comment by SebastianStehle** [comment]
We can just merge it and hope that it is fixed automatically. I had a similar problem with another build server  because it was always using an old commit for the PR check.

**Comment by richorama** [comment]
Just tried a rebase with a fresh PR, didn't work.

```
Errors in C:\projects\orleansdashboard\OrleansDashboard\OrleansDashboard.csproj
    NU1605: Detected package downgrade: System.Collections.Immutable from 1.5.0 to 1.4.0. Reference the package directly from the project to select a different version.
     OrleansDashboard -> Microsoft.AspNetCore.Hosting 2.1.1 -> System.Reflection.Metadata 1.6.0 -> System.Collections.Immutable (>= 1.5.0)
     OrleansDashboard -> System.Collections.Immutable (>= 1.4.0)
Errors in C:\projects\orleansdashboard\PerformanceTests\PerformanceTests.csproj
    NU1605: Detected package downgrade: System.Collections.Immutable from 1.5.0 to 1.4.0. Reference the package directly from the project to select a different version.
     PerformanceTests -> OrleansDashboard -> Microsoft.AspNetCore.Hosting 2.1.1 -> System.Reflection.Metadata 1.6.0 -> System.Collections.Immutable (>= 1.5.0)
     PerformanceTests -> OrleansDashboard -> System.Collections.Immutable (>= 1.4.0)
Errors in C:\projects\orleansdashboard\TestHostWindows\TestHostWindows.csproj
    NU1605: Detected package downgrade: System.Collections.Immutable from 1.5.0 to 1.4.0. Reference the package directly from the project to select a different version.
     TestHostWindows -> OrleansDashboard -> Microsoft.AspNetCore.Hosting 2.1.1 -> System.Reflection.Metadata 1.6.0 -> System.Collections.Immutable (>= 1.5.0)
     TestHostWindows -> OrleansDashboard -> System.Collections.Immutable (>= 1.4.0)
NuGet Config files used:
    C:\Users\appveyor\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
Feeds used:
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
    https://api.nuget.org/v3/index.json
    https://ci.appveyor.com/nuget/orleansdashboard-547et6s6oqco
    https://ci.appveyor.com/nuget/richorama-0llp5a4wkbyd
```

**Comment by SebastianStehle** [comment]
The reference to System.Collections.Immutable has been change later to the msater branch and I don't know why, but github does not show all changes. I have added the dependency to the PR now.

**Pull request merged**
