### PR TITLE
Support for embedded files.

### PR DESCRIPTION
**Pull request by SebastianStehle**
Closes https://github.com/OrleansContrib/OrleansDashboard/issues/308
Closes https://github.com/OrleansContrib/OrleansDashboard/issues/299

### CODE REVIEW

**Comment by SebastianStehle** [comment]
Sorry, VS reformatted the index.html. I hope it is okay. Otherwise I can also try to get your version back.

**Comment by richorama** [comment]
I'm still seeing some requests to google for some fonts, I'll see if I can fix this before publishing.
```
https://fonts.gstatic.com/s/sourcesanspro/v14/6xK3dSBYKcSV-LCoeQqfX1RYOo3qOK7l.woff2
https://fonts.gstatic.com/s/sourcesanspro/v14/6xKydSBYKcSV-LCoeQqfX1RYOo3ik4zwlxdu.woff2
https://fonts.gstatic.com/s/sourcesanspro/v14/6xKydSBYKcSV-LCoeQqfX1RYOo3ig4vwlxdu.woff2
https://fonts.gstatic.com/s/sourcesanspro/v14/6xK1dSBYKcSV-LCoeQqfX1RYOo3qPZ7nsDI.woff2
```

**Comment by SebastianStehle** [comment]
I have seen this, but I think it is acceptable if they are not loaded. Then the system should fall back to the default font and should be just fine. But honestly, I have not tested how it would look like without the fonts.

**Comment by richorama** [comment]
agreed.

**Comment by SebastianStehle** [comment]
I will test it and set a proper fallback font.

**Pull request merged**
