### PR TITLE
[WIP] .NET Core Support

### PR DESCRIPTION
**Pull request by ph1ll**
I am just starting to look at Orleans in general and this looks like a really useful project.

As Orleans is working towards .NET Core support (https://blogs.msdn.microsoft.com/orleans/2016/12/05/orleans-20-tech-preview-net-core/), it would be good to have .NET Core support here as well.

It looks like this would be relatively straight forward, the main issue being replacing nowin and owin and moving to something like Kestrel for the web server. 

I've done some initial work for this in this WIP PR, whilst trying not to change the structure too much and retaining full .NET 4.5.1 support.  Still have a little bit to do, but wanted to submit this for any initial feedback.

 * [x] Port OrleansDashboard
 * [x] Add Basic auth support back in
 * [x] Port TestGrains
 * [x] Port TestHost
 * [x] Port UnitTests

### CODE REVIEW

**Comment by ph1ll** [comment]
I think that should bring it up to a working netstandard port. 

This would need some changes to the CI/build commands, such as 

```
dotnet restore
dotnet test UnitTests
dotnet pack OrleansDashboard
```

Happy to make any tweaks desired. If this port is acceptable I can make the last tweaks for the dotnet build system, for example moving versions from `AssemblyInfo.cs` to `project.json` and adding other properties to `project.json` for nuget packaging (in place of the `.nuspec`)

**Comment by richorama** [comment]
Thank you for this awesome contribution! I'll take a look at the CI in the next day or so. :¬)

**Comment by richorama** [comment]
merged!

**Comment by richorama** [comment]
@ph1ll any idea on how to convert TestHost into an exe? My attempts so far have failed, but I'm very new to this core/netstandard stuff

**Comment by ph1ll** [comment]
It does take a bit of getting used to, the following article explains generating exes in full:

https://blogs.msdn.microsoft.com/luisdem/2016/10/11/net-core-how-to-publish-a-self-contained-application-exe/

But essentially you need to remove `"type": "platform"` from `project.json` and add a runtime section, such as:

```
"runtimes": { 
    "win7-x64": {}, 
    "ubuntu.14.04-x64": {} 
    } 
```

**Comment by richorama** [comment]
ah, that worked, thanks!

The other trick was to `dotnet publish` :¬)

**Pull request merged**
