### PR TITLE
Ring buffers

### PR DESCRIPTION
**Pull request by SebastianStehle**
It does not work yet, because I have an issue with the Code Generator.

The idea is to use Ring buffers for the history. Adding data should be almost allocation free and it should be faster due to memory locality and using an array instead of a linked list.

### CODE REVIEW

**Comment by richorama** [comment]
very cool idea :¬)

**Comment by SebastianStehle** [comment]
I have issues to run Benchmark.NET due to build problems with the code generator. So I also created a manual test:

```
Add V1: 00:00:00.0823485
Add V2: 00:00:00.0014637

Query All V1: 00:00:00.0345976
Query All V2: 00:00:00.0083909

Query By Silo V1: 00:00:00.0159898
Query By Silo V2: 00:00:00.0029655

Query By Grain V1: 00:00:00.0211149
Query By Grain V2: 00:00:00.0045666

Query By Grain and Silo V1: 00:00:00.0013156
Query By Grain and Silo V2: 00:00:00.0001551

Query Aggregated V1: 00:00:00.0006759
Query Aggregated V2: 00:00:00.0001269
```

**Comment by ReubenBond** [comment]
Taking a look now

**Comment by ReubenBond** [comment]
What is `IISi`? I can't find it: https://github.com/OrleansContrib/OrleansDashboard/blob/828a169fbaf67b859f29b177abafc103995aa80f/Tests/TestHosts/TestHost/Program.cs#L49

**Comment by SebastianStehle** [comment]
Nothing. We are in the middle of something. Only TestHostCohosted2 is working at the moment.

**Comment by ReubenBond** [comment]
Ok, I will run just the `PerformanceTests` project. So is it occasionally failing when Benchmark.NET itself is trying to perform the build, or is VS failing to build it?

**Comment by ReubenBond** [comment]
I'm not sure about running in VS, but when I run the `PerformanceTests` project from the commandline (`dotnet run -f net6.0 -c Release`), I get these errors about top level statements:
<details>
```
 rbn@rbn-dsk  C:        PerformanceTests  ring-buffers  dotnet run -f net6.0 -c Release
// Validating benchmarks:
// ***** BenchmarkRunner: Start   *****
// ***** Found 12 benchmark(s) in total *****
// ***** Building 1 exe(s) in Parallel: Start   *****
// start dotnet restore  /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true in C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83
// command took 1.14s and exited with 0
// start dotnet build -c Release  --no-restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true in C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83
// command took 1.85s and exited with 1
// start dotnet build -c Release  --no-restore --no-dependencies /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true in C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83
// command took 1.54s and exited with 1
// ***** Done, took 00:00:04 (4.63 sec)   *****
// Found 12 benchmarks:
//   DashboardGrainBenchmark.Test_Add_TraceHistory: ShortRun(IterationCount=3, LaunchCount=1, WarmupCount=3) [SiloCount=10, GrainTypeCount=50, GrainMethodCount=10, HistorySize=100, History=Orlea(...)story [45]]
//   DashboardGrainBenchmark.Test_QueryAll_TraceHistory: ShortRun(IterationCount=3, LaunchCount=1, WarmupCount=3) [SiloCount=10, GrainTypeCount=50, GrainMethodCount=10, HistorySize=100, History=Orlea(...)story [45]]
//   DashboardGrainBenchmark.Test_QuerySilo_TraceHistory: ShortRun(IterationCount=3, LaunchCount=1, WarmupCount=3) [SiloCount=10, GrainTypeCount=50, GrainMethodCount=10, HistorySize=100, History=Orlea(...)story [45]]
//   DashboardGrainBenchmark.Test_QueryGrain_TraceHistory: ShortRun(IterationCount=3, LaunchCount=1, WarmupCount=3) [SiloCount=10, GrainTypeCount=50, GrainMethodCount=10, HistorySize=100, History=Orlea(...)story [45]]
//   DashboardGrainBenchmark.Test_GroupByGrainAndSilo_TraceHistory: ShortRun(IterationCount=3, LaunchCount=1, WarmupCount=3) [SiloCount=10, GrainTypeCount=50, GrainMethodCount=10, HistorySize=100, History=Orlea(...)story [45]]
//   DashboardGrainBenchmark.Test_AggregateByGrainMethod_TraceHistory: ShortRun(IterationCount=3, LaunchCount=1, WarmupCount=3) [SiloCount=10, GrainTypeCount=50, GrainMethodCount=10, HistorySize=100, History=Orlea(...)story [45]]
//   DashboardGrainBenchmark.Test_Add_TraceHistory: ShortRun(IterationCount=3, LaunchCount=1, WarmupCount=3) [SiloCount=10, GrainTypeCount=50, GrainMethodCount=10, HistorySize=100, History=Orlea(...)oryV2 [47]]
//   DashboardGrainBenchmark.Test_QueryAll_TraceHistory: ShortRun(IterationCount=3, LaunchCount=1, WarmupCount=3) [SiloCount=10, GrainTypeCount=50, GrainMethodCount=10, HistorySize=100, History=Orlea(...)oryV2 [47]]
//   DashboardGrainBenchmark.Test_QuerySilo_TraceHistory: ShortRun(IterationCount=3, LaunchCount=1, WarmupCount=3) [SiloCount=10, GrainTypeCount=50, GrainMethodCount=10, HistorySize=100, History=Orlea(...)oryV2 [47]]
//   DashboardGrainBenchmark.Test_QueryGrain_TraceHistory: ShortRun(IterationCount=3, LaunchCount=1, WarmupCount=3) [SiloCount=10, GrainTypeCount=50, GrainMethodCount=10, HistorySize=100, History=Orlea(...)oryV2 [47]]
//   DashboardGrainBenchmark.Test_GroupByGrainAndSilo_TraceHistory: ShortRun(IterationCount=3, LaunchCount=1, WarmupCount=3) [SiloCount=10, GrainTypeCount=50, GrainMethodCount=10, HistorySize=100, History=Orlea(...)oryV2 [47]]
//   DashboardGrainBenchmark.Test_AggregateByGrainMethod_TraceHistory: ShortRun(IterationCount=3, LaunchCount=1, WarmupCount=3) [SiloCount=10, GrainTypeCount=50, GrainMethodCount=10, HistorySize=100, History=Orlea(...)oryV2 [47]]

// Build Error: Standard output:

 Standard error:
 Time Elapsed 00:00:01.36
    7 Error(s)
    0 Warning(s)
C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\6d59f925-f4da-49e0-859d-d041440fed83.orleans.g.cs(18,21): error CS0116: A namespace cannot directly contain members such as fields, methods or statements [C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\BenchmarkDotNet.Autogenerated.csproj]
C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\6d59f925-f4da-49e0-859d-d041440fed83.orleans.g.cs(10,12): error CS1729: 'TypeManifestProviderAttribute' does not contain a constructor that takes 4 arguments [C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\BenchmarkDotNet.Autogenerated.csproj]
C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\6d59f925-f4da-49e0-859d-d041440fed83.orleans.g.cs(10,178): error CS0103: The name 'd041440fed83' does not exist in the current context [C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\BenchmarkDotNet.Autogenerated.csproj]
C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\6d59f925-f4da-49e0-859d-d041440fed83.orleans.g.cs(10,163): error CS0103: The name 'f4da' does not exist in the current context [C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\BenchmarkDotNet.Autogenerated.csproj]
C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\6d59f925-f4da-49e0-859d-d041440fed83.orleans.g.cs(10,132): error CS0103: The name 'd041440fed83' does not exist in the current context [C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\BenchmarkDotNet.Autogenerated.csproj]
C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\6d59f925-f4da-49e0-859d-d041440fed83.orleans.g.cs(10,117): error CS0103: The name 'f4da' does not exist in the current context [C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\BenchmarkDotNet.Autogenerated.csproj]
C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\6d59f925-f4da-49e0-859d-d041440fed83.orleans.g.cs(10,93): error CS0118: 'OrleansCodeGen' is a namespace but is used like a type [C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\BenchmarkDotNet.Autogenerated.csproj]
Build FAILED.
C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\6d59f925-f4da-49e0-859d-d041440fed83.orleans.g.cs(18,21): error CS0116: A namespace cannot directly contain members such as fields, methods or statements [C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\BenchmarkDotNet.Autogenerated.csproj]
C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\6d59f925-f4da-49e0-859d-d041440fed83.orleans.g.cs(10,12): error CS1729: 'TypeManifestProviderAttribute' does not contain a constructor that takes 4 arguments [C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\BenchmarkDotNet.Autogenerated.csproj]
C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\6d59f925-f4da-49e0-859d-d041440fed83.orleans.g.cs(10,178): error CS0103: The name 'd041440fed83' does not exist in the current context [C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\BenchmarkDotNet.Autogenerated.csproj]
C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\6d59f925-f4da-49e0-859d-d041440fed83.orleans.g.cs(10,163): error CS0103: The name 'f4da' does not exist in the current context [C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\BenchmarkDotNet.Autogenerated.csproj]
C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\6d59f925-f4da-49e0-859d-d041440fed83.orleans.g.cs(10,132): error CS0103: The name 'd041440fed83' does not exist in the current context [C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\BenchmarkDotNet.Autogenerated.csproj]
C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\6d59f925-f4da-49e0-859d-d041440fed83.orleans.g.cs(10,117): error CS0103: The name 'f4da' does not exist in the current context [C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\BenchmarkDotNet.Autogenerated.csproj]
C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\6d59f925-f4da-49e0-859d-d041440fed83.orleans.g.cs(10,93): error CS0118: 'OrleansCodeGen' is a namespace but is used like a type [C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83\BenchmarkDotNet.Autogenerated.csproj]
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
Copyright (C) Microsoft Corporation. All rights reserved.
Microsoft (R) Build Engine version 17.1.0-preview-21610-01+96a618ca5 for .NET

// BenchmarkDotNet has failed to build the auto-generated boilerplate code.
// It can be found in C:\dev\OrleansDashboard\Tests\PerformanceTests\bin\Release\net6.0\6d59f925-f4da-49e0-859d-d041440fed83
// Please follow the troubleshooting guide: https://benchmarkdotnet.org/articles/guides/troubleshooting.html
// ***** BenchmarkRunner: Finish  *****

// * Export *
  BenchmarkDotNet.Artifacts\results\PerformanceTests.DashboardGrainBenchmark-report.csv
  BenchmarkDotNet.Artifacts\results\PerformanceTests.DashboardGrainBenchmark-report-github.md
  BenchmarkDotNet.Artifacts\results\PerformanceTests.DashboardGrainBenchmark-report.html

// * Detailed results *
DashboardGrainBenchmark.Test_Add_TraceHistory: ShortRun(IterationCount=3, LaunchCount=1, WarmupCount=3) [SiloCount=10, GrainTypeCount=50, GrainMethodCount=10, HistorySize=100, History=Orlea(...)story [45]]
Runtime = ; GC =
There are not any results runs

// * Summary *

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19044.1566 (21H2)
AMD Ryzen 9 3900X, 1 CPU, 24 logical and 12 physical cores
.NET SDK=6.0.200-preview.22055.15
  [Host] : .NET 6.0.1 (6.0.121.56705), X64 RyuJIT

Job=ShortRun  IterationCount=3  LaunchCount=1
WarmupCount=3

|                Method | SiloCount | GrainTypeCount | GrainMethodCount | HistorySize |              History | Mean | Error |
|---------------------- |---------- |--------------- |----------------- |------------ |--------------------- |-----:|------:|
| Test_Add_TraceHistory |        10 |             50 |               10 |         100 | Orlea(...)story [45] |   NA |    NA |

Benchmarks with issues:
  DashboardGrainBenchmark.Test_Add_TraceHistory: ShortRun(IterationCount=3, LaunchCount=1, WarmupCount=3) [SiloCount=10, GrainTypeCount=50, GrainMethodCount=10, HistorySize=100, History=Orlea(...)story [45]]

// * Legends *
  SiloCount        : Value of the 'SiloCount' parameter
  GrainTypeCount   : Value of the 'GrainTypeCount' parameter
  GrainMethodCount : Value of the 'GrainMethodCount' parameter
  HistorySize      : Value of the 'HistorySize' parameter
  History          : Value of the 'History' parameter
  Mean             : Arithmetic mean of all measurements
  Error            : Half of 99.9% confidence interval
  1 ns             : 1 Nanosecond (0.000000001 sec)

// * Diagnostic Output - MemoryDiagnoser *


// ***** BenchmarkRunner: End *****
// ** Remained 0 benchmark(s) to run **
Run time: 00:00:00 (0.19 sec), executed benchmarks: 0

Global total time: 00:00:04 (4.82 sec), executed benchmarks: 0
// * Artifacts cleanup *
```
</detail>

**Comment by ReubenBond** [comment]
Somehow this started to work for me. Still trying to work out why, but here are some results in the meantime:
```

|                                   Method | SiloCount | GrainTypeCount | GrainMethodCount | HistorySize |              History |        Mean |        Error |      StdDev |     Gen 0 |    Gen 1 | Allocated |
|----------------------------------------- |---------- |--------------- |----------------- |------------ |--------------------- |------------:|-------------:|------------:|----------:|---------:|----------:|
|                    Test_Add_TraceHistory |        10 |             50 |               10 |         100 | Orlea(...)story [45] | 96,431.0 us | 90,954.42 us | 4,985.52 us |         - |        - |    963 KB |
|               Test_QueryAll_TraceHistory |        10 |             50 |               10 |         100 | Orlea(...)story [45] | 27,538.6 us |  4,058.53 us |   222.46 us | 1562.5000 | 656.2500 | 12,865 KB |
|              Test_QuerySilo_TraceHistory |        10 |             50 |               10 |         100 | Orlea(...)story [45] | 13,144.9 us |  3,979.37 us |   218.12 us |   93.7500 |  31.2500 |    855 KB |
|             Test_QueryGrain_TraceHistory |        10 |             50 |               10 |         100 | Orlea(...)story [45] | 11,173.0 us |  5,719.05 us |   313.48 us |   93.7500 |  46.8750 |    846 KB |
|    Test_GroupByGrainAndSilo_TraceHistory |        10 |             50 |               10 |         100 | Orlea(...)story [45] | 48,465.7 us |  3,753.37 us |   205.73 us | 1000.0000 | 454.5455 |  8,224 KB |
| Test_AggregateByGrainMethod_TraceHistory |        10 |             50 |               10 |         100 | Orlea(...)story [45] | 61,952.8 us | 21,043.18 us | 1,153.45 us | 1000.0000 | 500.0000 |  8,233 KB |
|                    Test_Add_TraceHistory |        10 |             50 |               10 |         100 | Orlea(...)oryV2 [47] |    424.9 us |     59.41 us |     3.26 us |   23.4375 |        - |    195 KB |
|               Test_QueryAll_TraceHistory |        10 |             50 |               10 |         100 | Orlea(...)oryV2 [47] |  1,969.8 us |    184.65 us |    10.12 us |    9.7656 |        - |     96 KB |
|              Test_QuerySilo_TraceHistory |        10 |             50 |               10 |         100 | Orlea(...)oryV2 [47] |    324.2 us |     31.31 us |     1.72 us |    3.9063 |        - |     34 KB |
|             Test_QueryGrain_TraceHistory |        10 |             50 |               10 |         100 | Orlea(...)oryV2 [47] |    372.2 us |     19.48 us |     1.07 us |   22.9492 |   7.8125 |    188 KB |
|    Test_GroupByGrainAndSilo_TraceHistory |        10 |             50 |               10 |         100 | Orlea(...)oryV2 [47] |  2,423.2 us |    167.42 us |     9.18 us |   46.8750 |  15.6250 |    404 KB |
| Test_AggregateByGrainMethod_TraceHistory |        10 |             50 |               10 |         100 | Orlea(...)oryV2 [47] |  2,818.3 us |     98.54 us |     5.40 us |   46.8750 |  15.6250 |    412 KB |
```

**Comment by ReubenBond** [comment]
Alright, what makes it work is the last option here:
``` C#
            BenchmarkRunner.Run<DashboardGrainBenchmark>(
                ManualConfig.Create(DefaultConfig.Instance)
                    .WithOptions(ConfigOptions.DisableOptimizationsValidator)
                    .WithOption(ConfigOptions.KeepBenchmarkFiles, true));
```

I'm not sure why, I was just trying to make BDN keep the generated code around long enough for me to inspect it.

**Pull request merged**
