### PR TITLE
fix #296 default color scheme based on OS preference

### LINKED ISSUE #296: default the colour theme based on OS preference
https://gosink.in/javascript-css-toggle-dark-light-theme-based-on-your-users-preferred-scheme/

### PR DESCRIPTION
**Pull request by euronay**
Hi, 

In the spirit of Hacktoberfest I've given this a go. This will set the theme to the OS preference, but only if no theme preference has been saved to local storage.

I hope this is what you were after - let me know if you have any issues.

Cheers

James

### CODE REVIEW

**Comment by euronay** [comment]
Sorry - forgot to mention - if this is OK can you add the `hacktoberfest-accepted` label to the PR, please? 🙂

**Review by richorama — APPROVED** [review]

**Comment by richorama** [comment]
thank you! I will do a release in the next few days :¬)

**Comment by erictuvesson** [comment]
@euronay I believe the repository needs to have the hacktoberfest tag as well (think that is a new rule this year)

**Comment by euronay** [comment]
Hi @erictuvesson. It only needs the `hacktoberfest-accepted` tag if the repo does not have the hacktoberfest topic. So this is fine and I can see it counts on my hacktoberfest profile. 

Sorry for causing a fuss! I'm used to going by the the hacktoberfest tag on issues as I have done in past years.

**Pull request merged**
