### PR TITLE
Orleans 2.0

### PR DESCRIPTION
**Pull request by SebastianStehle**
I started to migrate everything to Orleans 2.0 and .NET Standard 2.0

I made very good progress and it is possible to either host the Dashboard self hosted or in a custom AspNetCore project (see TestHost vs TestHostSeparate). Some issues:

1. I tried to support different base paths in the dashboard, e.g. http://localhost:8080/dashboard/ but I don't know how to build the react app.
2. Metrics seem to be broken with 2.0
3. I don't know what to do with the Logs. I would like to have the option to disable it. But there is problem 1.
4. Dependencies of OrleansDashboard can be reduced but I have not done it yet. I have to remove the controller.

### CODE REVIEW

**Comment by SebastianStehle** [comment]
I think the whole performance counter stuff is not reliable anymore. We probably have to remove it from the dashboard or make it configurable to show it for Windows only. NetStandard does not support a common way to retrieve those information. Therefore Orleans does not support them.

**Comment by SebastianStehle** [comment]
I fixed the build and migrated the logging to the new .NET Core stuff. I also made a fix to the style of the log stream page.

What I would like to do:

1. Have an option to hide the log stream.
2. Show a "no data available" when CPU usage and memory usage is constantly 0. So as soon as Orleans fixes it we should get the correct data again. At least for Windows.

But as I said I have a problem with the build.

**Comment by richorama** [comment]
This is awesome work, big thanks!

I'll review early next week when I get the chance.

**Comment by SebastianStehle** [comment]
Just found the introduction to the UI stuff. I will fix the stuff :)

**Comment by SebastianStehle** [comment]
Everything done, waiting for review :)

**Comment by richorama** [comment]
I have been reviewing and trying it out - very impressed, thanks for this contribution!

I haven't been able to get the switch to disable the log stream to work. The options passed into the bootstrap provider are correct, but the constructor of the middleware always receives a `false` for `options.HideTrace`. Do the options need to be registered with the ASP.NET services?

**Comment by SebastianStehle** [comment]
I only tested it with the self host scenario. You are right, I guess we need to pass it to the WebHostBuilder in the Dashboard.cs

**Comment by richorama** [comment]
I've done that, and it now works correctly. Thanks.

I'm going to add this PE as a new branch, and maintain both 1.* and 2.* versions side-by-side. When Orleans 2.0 is released I'll switch that to the master branch.

**Comment by richorama** [comment]
This is now available on the `2.0` branch 

https://github.com/OrleansContrib/OrleansDashboard/tree/2.0

**Comment by richorama** [comment]
thanks for all your hard work @SebastianStehle!

**Comment by SebastianStehle** [comment]
No problem, I needed it ;) ... Can you publish it to Nuget?

**Comment by SebastianStehle** [comment]
Thx :)

**Pull request closed without merging**
